import yfinance as yf
import requests
import time
import json

epoch = 1665273600  # 9 Oct 2022 00:00:00 GMT


def return_None_on_error(func):
    def inner_func(*args, **kwargs):
        try:
            return func(*args, **kwargs)
        except Exception as e:
            print(f"{func.__name__} raised {e}")
            return None
    return inner_func


def parse_yahoo_api(r):
    r = json.loads(r)['timeseries']['result']
    parsed = {}
    for i in r:
        i.pop('meta')
        try:
            i.pop('timestamp')
        except KeyError:
            pass
        parsed.update(i)
    return parsed


def yahoo_api_get_balance_sheet_quarterly(ticker: str):
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36'}
    url = fr"https://query1.finance.yahoo.com/ws/fundamentals-timeseries/v1/finance/timeseries/{ticker}?lang=en-US&region=US&symbol={ticker}&padTimeSeries=true&type=quarterlyTreasurySharesNumber,trailingTreasurySharesNumber,quarterlyPreferredSharesNumber,trailingPreferredSharesNumber,quarterlyOrdinarySharesNumber,trailingOrdinarySharesNumber,quarterlyShareIssued,trailingShareIssued,quarterlyNetDebt,trailingNetDebt,quarterlyTotalDebt,trailingTotalDebt,quarterlyTangibleBookValue,trailingTangibleBookValue,quarterlyInvestedCapital,trailingInvestedCapital,quarterlyWorkingCapital,trailingWorkingCapital,quarterlyNetTangibleAssets,trailingNetTangibleAssets,quarterlyCapitalLeaseObligations,trailingCapitalLeaseObligations,quarterlyCommonStockEquity,trailingCommonStockEquity,quarterlyPreferredStockEquity,trailingPreferredStockEquity,quarterlyTotalCapitalization,trailingTotalCapitalization,quarterlyTotalEquityGrossMinorityInterest,trailingTotalEquityGrossMinorityInterest,quarterlyMinorityInterest,trailingMinorityInterest,quarterlyStockholdersEquity,trailingStockholdersEquity,quarterlyOtherEquityInterest,trailingOtherEquityInterest,quarterlyGainsLossesNotAffectingRetainedEarnings,trailingGainsLossesNotAffectingRetainedEarnings,quarterlyOtherEquityAdjustments,trailingOtherEquityAdjustments,quarterlyFixedAssetsRevaluationReserve,trailingFixedAssetsRevaluationReserve,quarterlyForeignCurrencyTranslationAdjustments,trailingForeignCurrencyTranslationAdjustments,quarterlyMinimumPensionLiabilities,trailingMinimumPensionLiabilities,quarterlyUnrealizedGainLoss,trailingUnrealizedGainLoss,quarterlyTreasuryStock,trailingTreasuryStock,quarterlyRetainedEarnings,trailingRetainedEarnings,quarterlyAdditionalPaidInCapital,trailingAdditionalPaidInCapital,quarterlyCapitalStock,trailingCapitalStock,quarterlyOtherCapitalStock,trailingOtherCapitalStock,quarterlyCommonStock,trailingCommonStock,quarterlyPreferredStock,trailingPreferredStock,quarterlyTotalPartnershipCapital,trailingTotalPartnershipCapital,quarterlyGeneralPartnershipCapital,trailingGeneralPartnershipCapital,quarterlyLimitedPartnershipCapital,trailingLimitedPartnershipCapital,quarterlyTotalLiabilitiesNetMinorityInterest,trailingTotalLiabilitiesNetMinorityInterest,quarterlyTotalNonCurrentLiabilitiesNetMinorityInterest,trailingTotalNonCurrentLiabilitiesNetMinorityInterest,quarterlyOtherNonCurrentLiabilities,trailingOtherNonCurrentLiabilities,quarterlyLiabilitiesHeldforSaleNonCurrent,trailingLiabilitiesHeldforSaleNonCurrent,quarterlyRestrictedCommonStock,trailingRestrictedCommonStock,quarterlyPreferredSecuritiesOutsideStockEquity,trailingPreferredSecuritiesOutsideStockEquity,quarterlyDerivativeProductLiabilities,trailingDerivativeProductLiabilities,quarterlyEmployeeBenefits,trailingEmployeeBenefits,quarterlyNonCurrentPensionAndOtherPostretirementBenefitPlans,trailingNonCurrentPensionAndOtherPostretirementBenefitPlans,quarterlyNonCurrentAccruedExpenses,trailingNonCurrentAccruedExpenses,quarterlyDuetoRelatedPartiesNonCurrent,trailingDuetoRelatedPartiesNonCurrent,quarterlyTradeandOtherPayablesNonCurrent,trailingTradeandOtherPayablesNonCurrent,quarterlyNonCurrentDeferredLiabilities,trailingNonCurrentDeferredLiabilities,quarterlyNonCurrentDeferredRevenue,trailingNonCurrentDeferredRevenue,quarterlyNonCurrentDeferredTaxesLiabilities,trailingNonCurrentDeferredTaxesLiabilities,quarterlyLongTermDebtAndCapitalLeaseObligation,trailingLongTermDebtAndCapitalLeaseObligation,quarterlyLongTermCapitalLeaseObligation,trailingLongTermCapitalLeaseObligation,quarterlyLongTermDebt,trailingLongTermDebt,quarterlyLongTermProvisions,trailingLongTermProvisions,quarterlyCurrentLiabilities,trailingCurrentLiabilities,quarterlyOtherCurrentLiabilities,trailingOtherCurrentLiabilities,quarterlyCurrentDeferredLiabilities,trailingCurrentDeferredLiabilities,quarterlyCurrentDeferredRevenue,trailingCurrentDeferredRevenue,quarterlyCurrentDeferredTaxesLiabilities,trailingCurrentDeferredTaxesLiabilities,quarterlyCurrentDebtAndCapitalLeaseObligation,trailingCurrentDebtAndCapitalLeaseObligation,quarterlyCurrentCapitalLeaseObligation,trailingCurrentCapitalLeaseObligation,quarterlyCurrentDebt,trailingCurrentDebt,quarterlyOtherCurrentBorrowings,trailingOtherCurrentBorrowings,quarterlyLineOfCredit,trailingLineOfCredit,quarterlyCommercialPaper,trailingCommercialPaper,quarterlyCurrentNotesPayable,trailingCurrentNotesPayable,quarterlyPensionandOtherPostRetirementBenefitPlansCurrent,trailingPensionandOtherPostRetirementBenefitPlansCurrent,quarterlyCurrentProvisions,trailingCurrentProvisions,quarterlyPayablesAndAccruedExpenses,trailingPayablesAndAccruedExpenses,quarterlyCurrentAccruedExpenses,trailingCurrentAccruedExpenses,quarterlyInterestPayable,trailingInterestPayable,quarterlyPayables,trailingPayables,quarterlyOtherPayable,trailingOtherPayable,quarterlyDuetoRelatedPartiesCurrent,trailingDuetoRelatedPartiesCurrent,quarterlyDividendsPayable,trailingDividendsPayable,quarterlyTotalTaxPayable,trailingTotalTaxPayable,quarterlyIncomeTaxPayable,trailingIncomeTaxPayable,quarterlyAccountsPayable,trailingAccountsPayable,quarterlyTotalAssets,trailingTotalAssets,quarterlyTotalNonCurrentAssets,trailingTotalNonCurrentAssets,quarterlyOtherNonCurrentAssets,trailingOtherNonCurrentAssets,quarterlyDefinedPensionBenefit,trailingDefinedPensionBenefit,quarterlyNonCurrentPrepaidAssets,trailingNonCurrentPrepaidAssets,quarterlyNonCurrentDeferredAssets,trailingNonCurrentDeferredAssets,quarterlyNonCurrentDeferredTaxesAssets,trailingNonCurrentDeferredTaxesAssets,quarterlyDuefromRelatedPartiesNonCurrent,trailingDuefromRelatedPartiesNonCurrent,quarterlyNonCurrentNoteReceivables,trailingNonCurrentNoteReceivables,quarterlyNonCurrentAccountsReceivable,trailingNonCurrentAccountsReceivable,quarterlyFinancialAssets,trailingFinancialAssets,quarterlyInvestmentsAndAdvances,trailingInvestmentsAndAdvances,quarterlyOtherInvestments,trailingOtherInvestments,quarterlyInvestmentinFinancialAssets,trailingInvestmentinFinancialAssets,quarterlyHeldToMaturitySecurities,trailingHeldToMaturitySecurities,quarterlyAvailableForSaleSecurities,trailingAvailableForSaleSecurities,quarterlyFinancialAssetsDesignatedasFairValueThroughProfitorLossTotal,trailingFinancialAssetsDesignatedasFairValueThroughProfitorLossTotal,quarterlyTradingSecurities,trailingTradingSecurities,quarterlyLongTermEquityInvestment,trailingLongTermEquityInvestment,quarterlyInvestmentsinJointVenturesatCost,trailingInvestmentsinJointVenturesatCost,quarterlyInvestmentsInOtherVenturesUnderEquityMethod,trailingInvestmentsInOtherVenturesUnderEquityMethod,quarterlyInvestmentsinAssociatesatCost,trailingInvestmentsinAssociatesatCost,quarterlyInvestmentsinSubsidiariesatCost,trailingInvestmentsinSubsidiariesatCost,quarterlyInvestmentProperties,trailingInvestmentProperties,quarterlyGoodwillAndOtherIntangibleAssets,trailingGoodwillAndOtherIntangibleAssets,quarterlyOtherIntangibleAssets,trailingOtherIntangibleAssets,quarterlyGoodwill,trailingGoodwill,quarterlyNetPPE,trailingNetPPE,quarterlyAccumulatedDepreciation,trailingAccumulatedDepreciation,quarterlyGrossPPE,trailingGrossPPE,quarterlyLeases,trailingLeases,quarterlyConstructionInProgress,trailingConstructionInProgress,quarterlyOtherProperties,trailingOtherProperties,quarterlyMachineryFurnitureEquipment,trailingMachineryFurnitureEquipment,quarterlyBuildingsAndImprovements,trailingBuildingsAndImprovements,quarterlyLandAndImprovements,trailingLandAndImprovements,quarterlyProperties,trailingProperties,quarterlyCurrentAssets,trailingCurrentAssets,quarterlyOtherCurrentAssets,trailingOtherCurrentAssets,quarterlyHedgingAssetsCurrent,trailingHedgingAssetsCurrent,quarterlyAssetsHeldForSaleCurrent,trailingAssetsHeldForSaleCurrent,quarterlyCurrentDeferredAssets,trailingCurrentDeferredAssets,quarterlyCurrentDeferredTaxesAssets,trailingCurrentDeferredTaxesAssets,quarterlyRestrictedCash,trailingRestrictedCash,quarterlyPrepaidAssets,trailingPrepaidAssets,quarterlyInventory,trailingInventory,quarterlyInventoriesAdjustmentsAllowances,trailingInventoriesAdjustmentsAllowances,quarterlyOtherInventories,trailingOtherInventories,quarterlyFinishedGoods,trailingFinishedGoods,quarterlyWorkInProcess,trailingWorkInProcess,quarterlyRawMaterials,trailingRawMaterials,quarterlyReceivables,trailingReceivables,quarterlyReceivablesAdjustmentsAllowances,trailingReceivablesAdjustmentsAllowances,quarterlyOtherReceivables,trailingOtherReceivables,quarterlyDuefromRelatedPartiesCurrent,trailingDuefromRelatedPartiesCurrent,quarterlyTaxesReceivable,trailingTaxesReceivable,quarterlyAccruedInterestReceivable,trailingAccruedInterestReceivable,quarterlyNotesReceivable,trailingNotesReceivable,quarterlyLoansReceivable,trailingLoansReceivable,quarterlyAccountsReceivable,trailingAccountsReceivable,quarterlyAllowanceForDoubtfulAccountsReceivable,trailingAllowanceForDoubtfulAccountsReceivable,quarterlyGrossAccountsReceivable,trailingGrossAccountsReceivable,quarterlyCashCashEquivalentsAndShortTermInvestments,trailingCashCashEquivalentsAndShortTermInvestments,quarterlyOtherShortTermInvestments,trailingOtherShortTermInvestments,quarterlyCashAndCashEquivalents,trailingCashAndCashEquivalents,quarterlyCashEquivalents,trailingCashEquivalents,quarterlyCashFinancial,trailingCashFinancial&merge=false&period1=06&period2={epoch}&corsDomain=finance.yahoo.com"
    r = requests.get(url, headers=headers).text
    return parse_yahoo_api(r)


def yahoo_api_get_balance_sheet_yearly(ticker: str):
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36'}
    url = fr"https://query1.finance.yahoo.com/ws/fundamentals-timeseries/v1/finance/timeseries/{ticker}?lang=en-US&region=US&symbol={ticker}&padTimeSeries=true&type=annualTreasurySharesNumber,trailingTreasurySharesNumber,annualPreferredSharesNumber,trailingPreferredSharesNumber,annualOrdinarySharesNumber,trailingOrdinarySharesNumber,annualShareIssued,trailingShareIssued,annualNetDebt,trailingNetDebt,annualTotalDebt,trailingTotalDebt,annualTangibleBookValue,trailingTangibleBookValue,annualInvestedCapital,trailingInvestedCapital,annualWorkingCapital,trailingWorkingCapital,annualNetTangibleAssets,trailingNetTangibleAssets,annualCapitalLeaseObligations,trailingCapitalLeaseObligations,annualCommonStockEquity,trailingCommonStockEquity,annualPreferredStockEquity,trailingPreferredStockEquity,annualTotalCapitalization,trailingTotalCapitalization,annualTotalEquityGrossMinorityInterest,trailingTotalEquityGrossMinorityInterest,annualMinorityInterest,trailingMinorityInterest,annualStockholdersEquity,trailingStockholdersEquity,annualOtherEquityInterest,trailingOtherEquityInterest,annualGainsLossesNotAffectingRetainedEarnings,trailingGainsLossesNotAffectingRetainedEarnings,annualOtherEquityAdjustments,trailingOtherEquityAdjustments,annualFixedAssetsRevaluationReserve,trailingFixedAssetsRevaluationReserve,annualForeignCurrencyTranslationAdjustments,trailingForeignCurrencyTranslationAdjustments,annualMinimumPensionLiabilities,trailingMinimumPensionLiabilities,annualUnrealizedGainLoss,trailingUnrealizedGainLoss,annualTreasuryStock,trailingTreasuryStock,annualRetainedEarnings,trailingRetainedEarnings,annualAdditionalPaidInCapital,trailingAdditionalPaidInCapital,annualCapitalStock,trailingCapitalStock,annualOtherCapitalStock,trailingOtherCapitalStock,annualCommonStock,trailingCommonStock,annualPreferredStock,trailingPreferredStock,annualTotalPartnershipCapital,trailingTotalPartnershipCapital,annualGeneralPartnershipCapital,trailingGeneralPartnershipCapital,annualLimitedPartnershipCapital,trailingLimitedPartnershipCapital,annualTotalLiabilitiesNetMinorityInterest,trailingTotalLiabilitiesNetMinorityInterest,annualTotalNonCurrentLiabilitiesNetMinorityInterest,trailingTotalNonCurrentLiabilitiesNetMinorityInterest,annualOtherNonCurrentLiabilities,trailingOtherNonCurrentLiabilities,annualLiabilitiesHeldforSaleNonCurrent,trailingLiabilitiesHeldforSaleNonCurrent,annualRestrictedCommonStock,trailingRestrictedCommonStock,annualPreferredSecuritiesOutsideStockEquity,trailingPreferredSecuritiesOutsideStockEquity,annualDerivativeProductLiabilities,trailingDerivativeProductLiabilities,annualEmployeeBenefits,trailingEmployeeBenefits,annualNonCurrentPensionAndOtherPostretirementBenefitPlans,trailingNonCurrentPensionAndOtherPostretirementBenefitPlans,annualNonCurrentAccruedExpenses,trailingNonCurrentAccruedExpenses,annualDuetoRelatedPartiesNonCurrent,trailingDuetoRelatedPartiesNonCurrent,annualTradeandOtherPayablesNonCurrent,trailingTradeandOtherPayablesNonCurrent,annualNonCurrentDeferredLiabilities,trailingNonCurrentDeferredLiabilities,annualNonCurrentDeferredRevenue,trailingNonCurrentDeferredRevenue,annualNonCurrentDeferredTaxesLiabilities,trailingNonCurrentDeferredTaxesLiabilities,annualLongTermDebtAndCapitalLeaseObligation,trailingLongTermDebtAndCapitalLeaseObligation,annualLongTermCapitalLeaseObligation,trailingLongTermCapitalLeaseObligation,annualLongTermDebt,trailingLongTermDebt,annualLongTermProvisions,trailingLongTermProvisions,annualCurrentLiabilities,trailingCurrentLiabilities,annualOtherCurrentLiabilities,trailingOtherCurrentLiabilities,annualCurrentDeferredLiabilities,trailingCurrentDeferredLiabilities,annualCurrentDeferredRevenue,trailingCurrentDeferredRevenue,annualCurrentDeferredTaxesLiabilities,trailingCurrentDeferredTaxesLiabilities,annualCurrentDebtAndCapitalLeaseObligation,trailingCurrentDebtAndCapitalLeaseObligation,annualCurrentCapitalLeaseObligation,trailingCurrentCapitalLeaseObligation,annualCurrentDebt,trailingCurrentDebt,annualOtherCurrentBorrowings,trailingOtherCurrentBorrowings,annualLineOfCredit,trailingLineOfCredit,annualCommercialPaper,trailingCommercialPaper,annualCurrentNotesPayable,trailingCurrentNotesPayable,annualPensionandOtherPostRetirementBenefitPlansCurrent,trailingPensionandOtherPostRetirementBenefitPlansCurrent,annualCurrentProvisions,trailingCurrentProvisions,annualPayablesAndAccruedExpenses,trailingPayablesAndAccruedExpenses,annualCurrentAccruedExpenses,trailingCurrentAccruedExpenses,annualInterestPayable,trailingInterestPayable,annualPayables,trailingPayables,annualOtherPayable,trailingOtherPayable,annualDuetoRelatedPartiesCurrent,trailingDuetoRelatedPartiesCurrent,annualDividendsPayable,trailingDividendsPayable,annualTotalTaxPayable,trailingTotalTaxPayable,annualIncomeTaxPayable,trailingIncomeTaxPayable,annualAccountsPayable,trailingAccountsPayable,annualTotalAssets,trailingTotalAssets,annualTotalNonCurrentAssets,trailingTotalNonCurrentAssets,annualOtherNonCurrentAssets,trailingOtherNonCurrentAssets,annualDefinedPensionBenefit,trailingDefinedPensionBenefit,annualNonCurrentPrepaidAssets,trailingNonCurrentPrepaidAssets,annualNonCurrentDeferredAssets,trailingNonCurrentDeferredAssets,annualNonCurrentDeferredTaxesAssets,trailingNonCurrentDeferredTaxesAssets,annualDuefromRelatedPartiesNonCurrent,trailingDuefromRelatedPartiesNonCurrent,annualNonCurrentNoteReceivables,trailingNonCurrentNoteReceivables,annualNonCurrentAccountsReceivable,trailingNonCurrentAccountsReceivable,annualFinancialAssets,trailingFinancialAssets,annualInvestmentsAndAdvances,trailingInvestmentsAndAdvances,annualOtherInvestments,trailingOtherInvestments,annualInvestmentinFinancialAssets,trailingInvestmentinFinancialAssets,annualHeldToMaturitySecurities,trailingHeldToMaturitySecurities,annualAvailableForSaleSecurities,trailingAvailableForSaleSecurities,annualFinancialAssetsDesignatedasFairValueThroughProfitorLossTotal,trailingFinancialAssetsDesignatedasFairValueThroughProfitorLossTotal,annualTradingSecurities,trailingTradingSecurities,annualLongTermEquityInvestment,trailingLongTermEquityInvestment,annualInvestmentsinJointVenturesatCost,trailingInvestmentsinJointVenturesatCost,annualInvestmentsInOtherVenturesUnderEquityMethod,trailingInvestmentsInOtherVenturesUnderEquityMethod,annualInvestmentsinAssociatesatCost,trailingInvestmentsinAssociatesatCost,annualInvestmentsinSubsidiariesatCost,trailingInvestmentsinSubsidiariesatCost,annualInvestmentProperties,trailingInvestmentProperties,annualGoodwillAndOtherIntangibleAssets,trailingGoodwillAndOtherIntangibleAssets,annualOtherIntangibleAssets,trailingOtherIntangibleAssets,annualGoodwill,trailingGoodwill,annualNetPPE,trailingNetPPE,annualAccumulatedDepreciation,trailingAccumulatedDepreciation,annualGrossPPE,trailingGrossPPE,annualLeases,trailingLeases,annualConstructionInProgress,trailingConstructionInProgress,annualOtherProperties,trailingOtherProperties,annualMachineryFurnitureEquipment,trailingMachineryFurnitureEquipment,annualBuildingsAndImprovements,trailingBuildingsAndImprovements,annualLandAndImprovements,trailingLandAndImprovements,annualProperties,trailingProperties,annualCurrentAssets,trailingCurrentAssets,annualOtherCurrentAssets,trailingOtherCurrentAssets,annualHedgingAssetsCurrent,trailingHedgingAssetsCurrent,annualAssetsHeldForSaleCurrent,trailingAssetsHeldForSaleCurrent,annualCurrentDeferredAssets,trailingCurrentDeferredAssets,annualCurrentDeferredTaxesAssets,trailingCurrentDeferredTaxesAssets,annualRestrictedCash,trailingRestrictedCash,annualPrepaidAssets,trailingPrepaidAssets,annualInventory,trailingInventory,annualInventoriesAdjustmentsAllowances,trailingInventoriesAdjustmentsAllowances,annualOtherInventories,trailingOtherInventories,annualFinishedGoods,trailingFinishedGoods,annualWorkInProcess,trailingWorkInProcess,annualRawMaterials,trailingRawMaterials,annualReceivables,trailingReceivables,annualReceivablesAdjustmentsAllowances,trailingReceivablesAdjustmentsAllowances,annualOtherReceivables,trailingOtherReceivables,annualDuefromRelatedPartiesCurrent,trailingDuefromRelatedPartiesCurrent,annualTaxesReceivable,trailingTaxesReceivable,annualAccruedInterestReceivable,trailingAccruedInterestReceivable,annualNotesReceivable,trailingNotesReceivable,annualLoansReceivable,trailingLoansReceivable,annualAccountsReceivable,trailingAccountsReceivable,annualAllowanceForDoubtfulAccountsReceivable,trailingAllowanceForDoubtfulAccountsReceivable,annualGrossAccountsReceivable,trailingGrossAccountsReceivable,annualCashCashEquivalentsAndShortTermInvestments,trailingCashCashEquivalentsAndShortTermInvestments,annualOtherShortTermInvestments,trailingOtherShortTermInvestments,annualCashAndCashEquivalents,trailingCashAndCashEquivalents,annualCashEquivalents,trailingCashEquivalents,annualCashFinancial,trailingCashFinancial&merge=false&period1=0&period2={epoch}&corsDomain=finance.yahoo.com"
    r = requests.get(url, headers=headers).text
    return parse_yahoo_api(r)


def yahoo_api_get_financials_quarterly(ticker: str):
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36'}
    url = fr"https://query2.finance.yahoo.com/ws/fundamentals-timeseries/v1/finance/timeseries/{ticker}?lang=en-US&region=US&symbol={ticker}&padTimeSeries=true&type=quarterlyTaxEffectOfUnusualItems,trailingTaxEffectOfUnusualItems,quarterlyTaxRateForCalcs,trailingTaxRateForCalcs,quarterlyNormalizedEBITDA,trailingNormalizedEBITDA,quarterlyNormalizedDilutedEPS,trailingNormalizedDilutedEPS,quarterlyNormalizedBasicEPS,trailingNormalizedBasicEPS,quarterlyTotalUnusualItems,trailingTotalUnusualItems,quarterlyTotalUnusualItemsExcludingGoodwill,trailingTotalUnusualItemsExcludingGoodwill,quarterlyNetIncomeFromContinuingOperationNetMinorityInterest,trailingNetIncomeFromContinuingOperationNetMinorityInterest,quarterlyReconciledDepreciation,trailingReconciledDepreciation,quarterlyReconciledCostOfRevenue,trailingReconciledCostOfRevenue,quarterlyEBITDA,trailingEBITDA,quarterlyEBIT,trailingEBIT,quarterlyNetInterestIncome,trailingNetInterestIncome,quarterlyInterestExpense,trailingInterestExpense,quarterlyInterestIncome,trailingInterestIncome,quarterlyContinuingAndDiscontinuedDilutedEPS,trailingContinuingAndDiscontinuedDilutedEPS,quarterlyContinuingAndDiscontinuedBasicEPS,trailingContinuingAndDiscontinuedBasicEPS,quarterlyNormalizedIncome,trailingNormalizedIncome,quarterlyNetIncomeFromContinuingAndDiscontinuedOperation,trailingNetIncomeFromContinuingAndDiscontinuedOperation,quarterlyTotalExpenses,trailingTotalExpenses,quarterlyRentExpenseSupplemental,trailingRentExpenseSupplemental,quarterlyReportedNormalizedDilutedEPS,trailingReportedNormalizedDilutedEPS,quarterlyReportedNormalizedBasicEPS,trailingReportedNormalizedBasicEPS,quarterlyTotalOperatingIncomeAsReported,trailingTotalOperatingIncomeAsReported,quarterlyDividendPerShare,trailingDividendPerShare,quarterlyDilutedAverageShares,trailingDilutedAverageShares,quarterlyBasicAverageShares,trailingBasicAverageShares,quarterlyDilutedEPS,trailingDilutedEPS,quarterlyDilutedEPSOtherGainsLosses,trailingDilutedEPSOtherGainsLosses,quarterlyTaxLossCarryforwardDilutedEPS,trailingTaxLossCarryforwardDilutedEPS,quarterlyDilutedAccountingChange,trailingDilutedAccountingChange,quarterlyDilutedExtraordinary,trailingDilutedExtraordinary,quarterlyDilutedDiscontinuousOperations,trailingDilutedDiscontinuousOperations,quarterlyDilutedContinuousOperations,trailingDilutedContinuousOperations,quarterlyBasicEPS,trailingBasicEPS,quarterlyBasicEPSOtherGainsLosses,trailingBasicEPSOtherGainsLosses,quarterlyTaxLossCarryforwardBasicEPS,trailingTaxLossCarryforwardBasicEPS,quarterlyBasicAccountingChange,trailingBasicAccountingChange,quarterlyBasicExtraordinary,trailingBasicExtraordinary,quarterlyBasicDiscontinuousOperations,trailingBasicDiscontinuousOperations,quarterlyBasicContinuousOperations,trailingBasicContinuousOperations,quarterlyDilutedNIAvailtoComStockholders,trailingDilutedNIAvailtoComStockholders,quarterlyAverageDilutionEarnings,trailingAverageDilutionEarnings,quarterlyNetIncomeCommonStockholders,trailingNetIncomeCommonStockholders,quarterlyOtherunderPreferredStockDividend,trailingOtherunderPreferredStockDividend,quarterlyPreferredStockDividends,trailingPreferredStockDividends,quarterlyNetIncome,trailingNetIncome,quarterlyMinorityInterests,trailingMinorityInterests,quarterlyNetIncomeIncludingNoncontrollingInterests,trailingNetIncomeIncludingNoncontrollingInterests,quarterlyNetIncomeFromTaxLossCarryforward,trailingNetIncomeFromTaxLossCarryforward,quarterlyNetIncomeExtraordinary,trailingNetIncomeExtraordinary,quarterlyNetIncomeDiscontinuousOperations,trailingNetIncomeDiscontinuousOperations,quarterlyNetIncomeContinuousOperations,trailingNetIncomeContinuousOperations,quarterlyEarningsFromEquityInterestNetOfTax,trailingEarningsFromEquityInterestNetOfTax,quarterlyTaxProvision,trailingTaxProvision,quarterlyPretaxIncome,trailingPretaxIncome,quarterlyOtherIncomeExpense,trailingOtherIncomeExpense,quarterlyOtherNonOperatingIncomeExpenses,trailingOtherNonOperatingIncomeExpenses,quarterlySpecialIncomeCharges,trailingSpecialIncomeCharges,quarterlyGainOnSaleOfPPE,trailingGainOnSaleOfPPE,quarterlyGainOnSaleOfBusiness,trailingGainOnSaleOfBusiness,quarterlyOtherSpecialCharges,trailingOtherSpecialCharges,quarterlyWriteOff,trailingWriteOff,quarterlyImpairmentOfCapitalAssets,trailingImpairmentOfCapitalAssets,quarterlyRestructuringAndMergernAcquisition,trailingRestructuringAndMergernAcquisition,quarterlySecuritiesAmortization,trailingSecuritiesAmortization,quarterlyEarningsFromEquityInterest,trailingEarningsFromEquityInterest,quarterlyGainOnSaleOfSecurity,trailingGainOnSaleOfSecurity,quarterlyNetNonOperatingInterestIncomeExpense,trailingNetNonOperatingInterestIncomeExpense,quarterlyTotalOtherFinanceCost,trailingTotalOtherFinanceCost,quarterlyInterestExpenseNonOperating,trailingInterestExpenseNonOperating,quarterlyInterestIncomeNonOperating,trailingInterestIncomeNonOperating,quarterlyOperatingIncome,trailingOperatingIncome,quarterlyOperatingExpense,trailingOperatingExpense,quarterlyOtherOperatingExpenses,trailingOtherOperatingExpenses,quarterlyOtherTaxes,trailingOtherTaxes,quarterlyProvisionForDoubtfulAccounts,trailingProvisionForDoubtfulAccounts,quarterlyDepreciationAmortizationDepletionIncomeStatement,trailingDepreciationAmortizationDepletionIncomeStatement,quarterlyDepletionIncomeStatement,trailingDepletionIncomeStatement,quarterlyDepreciationAndAmortizationInIncomeStatement,trailingDepreciationAndAmortizationInIncomeStatement,quarterlyAmortization,trailingAmortization,quarterlyAmortizationOfIntangiblesIncomeStatement,trailingAmortizationOfIntangiblesIncomeStatement,quarterlyDepreciationIncomeStatement,trailingDepreciationIncomeStatement,quarterlyResearchAndDevelopment,trailingResearchAndDevelopment,quarterlySellingGeneralAndAdministration,trailingSellingGeneralAndAdministration,quarterlySellingAndMarketingExpense,trailingSellingAndMarketingExpense,quarterlyGeneralAndAdministrativeExpense,trailingGeneralAndAdministrativeExpense,quarterlyOtherGandA,trailingOtherGandA,quarterlyInsuranceAndClaims,trailingInsuranceAndClaims,quarterlyRentAndLandingFees,trailingRentAndLandingFees,quarterlySalariesAndWages,trailingSalariesAndWages,quarterlyGrossProfit,trailingGrossProfit,quarterlyCostOfRevenue,trailingCostOfRevenue,quarterlyTotalRevenue,trailingTotalRevenue,quarterlyExciseTaxes,trailingExciseTaxes,quarterlyOperatingRevenue,trailingOperatingRevenue&merge=false&period1=0&period2={epoch}&corsDomain=finance.yahoo.com"
    r = requests.get(url, headers=headers).text
    return parse_yahoo_api(r)


def yahoo_api_get_financials_yearly(ticker: str):
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36'}
    url = fr"https://query1.finance.yahoo.com/ws/fundamentals-timeseries/v1/finance/timeseries/{ticker}?lang=en-US&region=US&symbol={ticker}&padTimeSeries=true&type=annualTaxEffectOfUnusualItems,trailingTaxEffectOfUnusualItems,annualTaxRateForCalcs,trailingTaxRateForCalcs,annualNormalizedEBITDA,trailingNormalizedEBITDA,annualNormalizedDilutedEPS,trailingNormalizedDilutedEPS,annualNormalizedBasicEPS,trailingNormalizedBasicEPS,annualTotalUnusualItems,trailingTotalUnusualItems,annualTotalUnusualItemsExcludingGoodwill,trailingTotalUnusualItemsExcludingGoodwill,annualNetIncomeFromContinuingOperationNetMinorityInterest,trailingNetIncomeFromContinuingOperationNetMinorityInterest,annualReconciledDepreciation,trailingReconciledDepreciation,annualReconciledCostOfRevenue,trailingReconciledCostOfRevenue,annualEBITDA,trailingEBITDA,annualEBIT,trailingEBIT,annualNetInterestIncome,trailingNetInterestIncome,annualInterestExpense,trailingInterestExpense,annualInterestIncome,trailingInterestIncome,annualContinuingAndDiscontinuedDilutedEPS,trailingContinuingAndDiscontinuedDilutedEPS,annualContinuingAndDiscontinuedBasicEPS,trailingContinuingAndDiscontinuedBasicEPS,annualNormalizedIncome,trailingNormalizedIncome,annualNetIncomeFromContinuingAndDiscontinuedOperation,trailingNetIncomeFromContinuingAndDiscontinuedOperation,annualTotalExpenses,trailingTotalExpenses,annualRentExpenseSupplemental,trailingRentExpenseSupplemental,annualReportedNormalizedDilutedEPS,trailingReportedNormalizedDilutedEPS,annualReportedNormalizedBasicEPS,trailingReportedNormalizedBasicEPS,annualTotalOperatingIncomeAsReported,trailingTotalOperatingIncomeAsReported,annualDividendPerShare,trailingDividendPerShare,annualDilutedAverageShares,trailingDilutedAverageShares,annualBasicAverageShares,trailingBasicAverageShares,annualDilutedEPS,trailingDilutedEPS,annualDilutedEPSOtherGainsLosses,trailingDilutedEPSOtherGainsLosses,annualTaxLossCarryforwardDilutedEPS,trailingTaxLossCarryforwardDilutedEPS,annualDilutedAccountingChange,trailingDilutedAccountingChange,annualDilutedExtraordinary,trailingDilutedExtraordinary,annualDilutedDiscontinuousOperations,trailingDilutedDiscontinuousOperations,annualDilutedContinuousOperations,trailingDilutedContinuousOperations,annualBasicEPS,trailingBasicEPS,annualBasicEPSOtherGainsLosses,trailingBasicEPSOtherGainsLosses,annualTaxLossCarryforwardBasicEPS,trailingTaxLossCarryforwardBasicEPS,annualBasicAccountingChange,trailingBasicAccountingChange,annualBasicExtraordinary,trailingBasicExtraordinary,annualBasicDiscontinuousOperations,trailingBasicDiscontinuousOperations,annualBasicContinuousOperations,trailingBasicContinuousOperations,annualDilutedNIAvailtoComStockholders,trailingDilutedNIAvailtoComStockholders,annualAverageDilutionEarnings,trailingAverageDilutionEarnings,annualNetIncomeCommonStockholders,trailingNetIncomeCommonStockholders,annualOtherunderPreferredStockDividend,trailingOtherunderPreferredStockDividend,annualPreferredStockDividends,trailingPreferredStockDividends,annualNetIncome,trailingNetIncome,annualMinorityInterests,trailingMinorityInterests,annualNetIncomeIncludingNoncontrollingInterests,trailingNetIncomeIncludingNoncontrollingInterests,annualNetIncomeFromTaxLossCarryforward,trailingNetIncomeFromTaxLossCarryforward,annualNetIncomeExtraordinary,trailingNetIncomeExtraordinary,annualNetIncomeDiscontinuousOperations,trailingNetIncomeDiscontinuousOperations,annualNetIncomeContinuousOperations,trailingNetIncomeContinuousOperations,annualEarningsFromEquityInterestNetOfTax,trailingEarningsFromEquityInterestNetOfTax,annualTaxProvision,trailingTaxProvision,annualPretaxIncome,trailingPretaxIncome,annualOtherIncomeExpense,trailingOtherIncomeExpense,annualOtherNonOperatingIncomeExpenses,trailingOtherNonOperatingIncomeExpenses,annualSpecialIncomeCharges,trailingSpecialIncomeCharges,annualGainOnSaleOfPPE,trailingGainOnSaleOfPPE,annualGainOnSaleOfBusiness,trailingGainOnSaleOfBusiness,annualOtherSpecialCharges,trailingOtherSpecialCharges,annualWriteOff,trailingWriteOff,annualImpairmentOfCapitalAssets,trailingImpairmentOfCapitalAssets,annualRestructuringAndMergernAcquisition,trailingRestructuringAndMergernAcquisition,annualSecuritiesAmortization,trailingSecuritiesAmortization,annualEarningsFromEquityInterest,trailingEarningsFromEquityInterest,annualGainOnSaleOfSecurity,trailingGainOnSaleOfSecurity,annualNetNonOperatingInterestIncomeExpense,trailingNetNonOperatingInterestIncomeExpense,annualTotalOtherFinanceCost,trailingTotalOtherFinanceCost,annualInterestExpenseNonOperating,trailingInterestExpenseNonOperating,annualInterestIncomeNonOperating,trailingInterestIncomeNonOperating,annualOperatingIncome,trailingOperatingIncome,annualOperatingExpense,trailingOperatingExpense,annualOtherOperatingExpenses,trailingOtherOperatingExpenses,annualOtherTaxes,trailingOtherTaxes,annualProvisionForDoubtfulAccounts,trailingProvisionForDoubtfulAccounts,annualDepreciationAmortizationDepletionIncomeStatement,trailingDepreciationAmortizationDepletionIncomeStatement,annualDepletionIncomeStatement,trailingDepletionIncomeStatement,annualDepreciationAndAmortizationInIncomeStatement,trailingDepreciationAndAmortizationInIncomeStatement,annualAmortization,trailingAmortization,annualAmortizationOfIntangiblesIncomeStatement,trailingAmortizationOfIntangiblesIncomeStatement,annualDepreciationIncomeStatement,trailingDepreciationIncomeStatement,annualResearchAndDevelopment,trailingResearchAndDevelopment,annualSellingGeneralAndAdministration,trailingSellingGeneralAndAdministration,annualSellingAndMarketingExpense,trailingSellingAndMarketingExpense,annualGeneralAndAdministrativeExpense,trailingGeneralAndAdministrativeExpense,annualOtherGandA,trailingOtherGandA,annualInsuranceAndClaims,trailingInsuranceAndClaims,annualRentAndLandingFees,trailingRentAndLandingFees,annualSalariesAndWages,trailingSalariesAndWages,annualGrossProfit,trailingGrossProfit,annualCostOfRevenue,trailingCostOfRevenue,annualTotalRevenue,trailingTotalRevenue,annualExciseTaxes,trailingExciseTaxes,annualOperatingRevenue,trailingOperatingRevenue&merge=false&period1=0&period2={epoch}&corsDomain=finance.yahoo.com"
    r = requests.get(url, headers=headers).text
    return parse_yahoo_api(r)


def yahoo_api_get_cashflow_quarterly(ticker: str):
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36'}
    url = fr"https://query1.finance.yahoo.com/ws/fundamentals-timeseries/v1/finance/timeseries/{ticker}?lang=en-US&region=US&symbol={ticker}&padTimeSeries=true&type=quarterlyForeignSales,trailingForeignSales,quarterlyDomesticSales,trailingDomesticSales,quarterlyAdjustedGeographySegmentData,trailingAdjustedGeographySegmentData,quarterlyFreeCashFlow,trailingFreeCashFlow,quarterlyRepurchaseOfCapitalStock,trailingRepurchaseOfCapitalStock,quarterlyRepaymentOfDebt,trailingRepaymentOfDebt,quarterlyIssuanceOfDebt,trailingIssuanceOfDebt,quarterlyIssuanceOfCapitalStock,trailingIssuanceOfCapitalStock,quarterlyCapitalExpenditure,trailingCapitalExpenditure,quarterlyInterestPaidSupplementalData,trailingInterestPaidSupplementalData,quarterlyIncomeTaxPaidSupplementalData,trailingIncomeTaxPaidSupplementalData,quarterlyEndCashPosition,trailingEndCashPosition,quarterlyOtherCashAdjustmentOutsideChangeinCash,trailingOtherCashAdjustmentOutsideChangeinCash,quarterlyBeginningCashPosition,trailingBeginningCashPosition,quarterlyEffectOfExchangeRateChanges,trailingEffectOfExchangeRateChanges,quarterlyChangesInCash,trailingChangesInCash,quarterlyOtherCashAdjustmentInsideChangeinCash,trailingOtherCashAdjustmentInsideChangeinCash,quarterlyCashFlowFromDiscontinuedOperation,trailingCashFlowFromDiscontinuedOperation,quarterlyFinancingCashFlow,trailingFinancingCashFlow,quarterlyCashFromDiscontinuedFinancingActivities,trailingCashFromDiscontinuedFinancingActivities,quarterlyCashFlowFromContinuingFinancingActivities,trailingCashFlowFromContinuingFinancingActivities,quarterlyNetOtherFinancingCharges,trailingNetOtherFinancingCharges,quarterlyInterestPaidCFF,trailingInterestPaidCFF,quarterlyProceedsFromStockOptionExercised,trailingProceedsFromStockOptionExercised,quarterlyCashDividendsPaid,trailingCashDividendsPaid,quarterlyPreferredStockDividendPaid,trailingPreferredStockDividendPaid,quarterlyCommonStockDividendPaid,trailingCommonStockDividendPaid,quarterlyNetPreferredStockIssuance,trailingNetPreferredStockIssuance,quarterlyPreferredStockPayments,trailingPreferredStockPayments,quarterlyPreferredStockIssuance,trailingPreferredStockIssuance,quarterlyNetCommonStockIssuance,trailingNetCommonStockIssuance,quarterlyCommonStockPayments,trailingCommonStockPayments,quarterlyCommonStockIssuance,trailingCommonStockIssuance,quarterlyNetIssuancePaymentsOfDebt,trailingNetIssuancePaymentsOfDebt,quarterlyNetShortTermDebtIssuance,trailingNetShortTermDebtIssuance,quarterlyShortTermDebtPayments,trailingShortTermDebtPayments,quarterlyShortTermDebtIssuance,trailingShortTermDebtIssuance,quarterlyNetLongTermDebtIssuance,trailingNetLongTermDebtIssuance,quarterlyLongTermDebtPayments,trailingLongTermDebtPayments,quarterlyLongTermDebtIssuance,trailingLongTermDebtIssuance,quarterlyInvestingCashFlow,trailingInvestingCashFlow,quarterlyCashFromDiscontinuedInvestingActivities,trailingCashFromDiscontinuedInvestingActivities,quarterlyCashFlowFromContinuingInvestingActivities,trailingCashFlowFromContinuingInvestingActivities,quarterlyNetOtherInvestingChanges,trailingNetOtherInvestingChanges,quarterlyInterestReceivedCFI,trailingInterestReceivedCFI,quarterlyDividendsReceivedCFI,trailingDividendsReceivedCFI,quarterlyNetInvestmentPurchaseAndSale,trailingNetInvestmentPurchaseAndSale,quarterlySaleOfInvestment,trailingSaleOfInvestment,quarterlyPurchaseOfInvestment,trailingPurchaseOfInvestment,quarterlyNetInvestmentPropertiesPurchaseAndSale,trailingNetInvestmentPropertiesPurchaseAndSale,quarterlySaleOfInvestmentProperties,trailingSaleOfInvestmentProperties,quarterlyPurchaseOfInvestmentProperties,trailingPurchaseOfInvestmentProperties,quarterlyNetBusinessPurchaseAndSale,trailingNetBusinessPurchaseAndSale,quarterlySaleOfBusiness,trailingSaleOfBusiness,quarterlyPurchaseOfBusiness,trailingPurchaseOfBusiness,quarterlyNetIntangiblesPurchaseAndSale,trailingNetIntangiblesPurchaseAndSale,quarterlySaleOfIntangibles,trailingSaleOfIntangibles,quarterlyPurchaseOfIntangibles,trailingPurchaseOfIntangibles,quarterlyNetPPEPurchaseAndSale,trailingNetPPEPurchaseAndSale,quarterlySaleOfPPE,trailingSaleOfPPE,quarterlyPurchaseOfPPE,trailingPurchaseOfPPE,quarterlyCapitalExpenditureReported,trailingCapitalExpenditureReported,quarterlyOperatingCashFlow,trailingOperatingCashFlow,quarterlyCashFromDiscontinuedOperatingActivities,trailingCashFromDiscontinuedOperatingActivities,quarterlyCashFlowFromContinuingOperatingActivities,trailingCashFlowFromContinuingOperatingActivities,quarterlyTaxesRefundPaid,trailingTaxesRefundPaid,quarterlyInterestReceivedCFO,trailingInterestReceivedCFO,quarterlyInterestPaidCFO,trailingInterestPaidCFO,quarterlyDividendReceivedCFO,trailingDividendReceivedCFO,quarterlyDividendPaidCFO,trailingDividendPaidCFO,quarterlyChangeInWorkingCapital,trailingChangeInWorkingCapital,quarterlyChangeInOtherWorkingCapital,trailingChangeInOtherWorkingCapital,quarterlyChangeInOtherCurrentLiabilities,trailingChangeInOtherCurrentLiabilities,quarterlyChangeInOtherCurrentAssets,trailingChangeInOtherCurrentAssets,quarterlyChangeInPayablesAndAccruedExpense,trailingChangeInPayablesAndAccruedExpense,quarterlyChangeInAccruedExpense,trailingChangeInAccruedExpense,quarterlyChangeInInterestPayable,trailingChangeInInterestPayable,quarterlyChangeInPayable,trailingChangeInPayable,quarterlyChangeInDividendPayable,trailingChangeInDividendPayable,quarterlyChangeInAccountPayable,trailingChangeInAccountPayable,quarterlyChangeInTaxPayable,trailingChangeInTaxPayable,quarterlyChangeInIncomeTaxPayable,trailingChangeInIncomeTaxPayable,quarterlyChangeInPrepaidAssets,trailingChangeInPrepaidAssets,quarterlyChangeInInventory,trailingChangeInInventory,quarterlyChangeInReceivables,trailingChangeInReceivables,quarterlyChangesInAccountReceivables,trailingChangesInAccountReceivables,quarterlyOtherNonCashItems,trailingOtherNonCashItems,quarterlyExcessTaxBenefitFromStockBasedCompensation,trailingExcessTaxBenefitFromStockBasedCompensation,quarterlyStockBasedCompensation,trailingStockBasedCompensation,quarterlyUnrealizedGainLossOnInvestmentSecurities,trailingUnrealizedGainLossOnInvestmentSecurities,quarterlyProvisionandWriteOffofAssets,trailingProvisionandWriteOffofAssets,quarterlyAssetImpairmentCharge,trailingAssetImpairmentCharge,quarterlyAmortizationOfSecurities,trailingAmortizationOfSecurities,quarterlyDeferredTax,trailingDeferredTax,quarterlyDeferredIncomeTax,trailingDeferredIncomeTax,quarterlyDepreciationAmortizationDepletion,trailingDepreciationAmortizationDepletion,quarterlyDepletion,trailingDepletion,quarterlyDepreciationAndAmortization,trailingDepreciationAndAmortization,quarterlyAmortizationCashFlow,trailingAmortizationCashFlow,quarterlyAmortizationOfIntangibles,trailingAmortizationOfIntangibles,quarterlyDepreciation,trailingDepreciation,quarterlyOperatingGainsLosses,trailingOperatingGainsLosses,quarterlyPensionAndEmployeeBenefitExpense,trailingPensionAndEmployeeBenefitExpense,quarterlyEarningsLossesFromEquityInvestments,trailingEarningsLossesFromEquityInvestments,quarterlyGainLossOnInvestmentSecurities,trailingGainLossOnInvestmentSecurities,quarterlyNetForeignCurrencyExchangeGainLoss,trailingNetForeignCurrencyExchangeGainLoss,quarterlyGainLossOnSaleOfPPE,trailingGainLossOnSaleOfPPE,quarterlyGainLossOnSaleOfBusiness,trailingGainLossOnSaleOfBusiness,quarterlyNetIncomeFromContinuingOperations,trailingNetIncomeFromContinuingOperations,quarterlyCashFlowsfromusedinOperatingActivitiesDirect,trailingCashFlowsfromusedinOperatingActivitiesDirect,quarterlyTaxesRefundPaidDirect,trailingTaxesRefundPaidDirect,quarterlyInterestReceivedDirect,trailingInterestReceivedDirect,quarterlyInterestPaidDirect,trailingInterestPaidDirect,quarterlyDividendsReceivedDirect,trailingDividendsReceivedDirect,quarterlyDividendsPaidDirect,trailingDividendsPaidDirect,quarterlyClassesofCashPayments,trailingClassesofCashPayments,quarterlyOtherCashPaymentsfromOperatingActivities,trailingOtherCashPaymentsfromOperatingActivities,quarterlyPaymentsonBehalfofEmployees,trailingPaymentsonBehalfofEmployees,quarterlyPaymentstoSuppliersforGoodsandServices,trailingPaymentstoSuppliersforGoodsandServices,quarterlyClassesofCashReceiptsfromOperatingActivities,trailingClassesofCashReceiptsfromOperatingActivities,quarterlyOtherCashReceiptsfromOperatingActivities,trailingOtherCashReceiptsfromOperatingActivities,quarterlyReceiptsfromGovernmentGrants,trailingReceiptsfromGovernmentGrants,quarterlyReceiptsfromCustomers,trailingReceiptsfromCustomers&merge=false&period1=0&period2={epoch}&corsDomain=finance.yahoo.com"
    r = requests.get(url, headers=headers).text
    return parse_yahoo_api(r)


def yahoo_api_get_cashflow_yearly(ticker: str):
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36'}
    url = fr"https://query1.finance.yahoo.com/ws/fundamentals-timeseries/v1/finance/timeseries/{ticker}?lang=en-US&region=US&symbol={ticker}&padTimeSeries=true&type=annualForeignSales,trailingForeignSales,annualDomesticSales,trailingDomesticSales,annualAdjustedGeographySegmentData,trailingAdjustedGeographySegmentData,annualFreeCashFlow,trailingFreeCashFlow,annualRepurchaseOfCapitalStock,trailingRepurchaseOfCapitalStock,annualRepaymentOfDebt,trailingRepaymentOfDebt,annualIssuanceOfDebt,trailingIssuanceOfDebt,annualIssuanceOfCapitalStock,trailingIssuanceOfCapitalStock,annualCapitalExpenditure,trailingCapitalExpenditure,annualInterestPaidSupplementalData,trailingInterestPaidSupplementalData,annualIncomeTaxPaidSupplementalData,trailingIncomeTaxPaidSupplementalData,annualEndCashPosition,trailingEndCashPosition,annualOtherCashAdjustmentOutsideChangeinCash,trailingOtherCashAdjustmentOutsideChangeinCash,annualBeginningCashPosition,trailingBeginningCashPosition,annualEffectOfExchangeRateChanges,trailingEffectOfExchangeRateChanges,annualChangesInCash,trailingChangesInCash,annualOtherCashAdjustmentInsideChangeinCash,trailingOtherCashAdjustmentInsideChangeinCash,annualCashFlowFromDiscontinuedOperation,trailingCashFlowFromDiscontinuedOperation,annualFinancingCashFlow,trailingFinancingCashFlow,annualCashFromDiscontinuedFinancingActivities,trailingCashFromDiscontinuedFinancingActivities,annualCashFlowFromContinuingFinancingActivities,trailingCashFlowFromContinuingFinancingActivities,annualNetOtherFinancingCharges,trailingNetOtherFinancingCharges,annualInterestPaidCFF,trailingInterestPaidCFF,annualProceedsFromStockOptionExercised,trailingProceedsFromStockOptionExercised,annualCashDividendsPaid,trailingCashDividendsPaid,annualPreferredStockDividendPaid,trailingPreferredStockDividendPaid,annualCommonStockDividendPaid,trailingCommonStockDividendPaid,annualNetPreferredStockIssuance,trailingNetPreferredStockIssuance,annualPreferredStockPayments,trailingPreferredStockPayments,annualPreferredStockIssuance,trailingPreferredStockIssuance,annualNetCommonStockIssuance,trailingNetCommonStockIssuance,annualCommonStockPayments,trailingCommonStockPayments,annualCommonStockIssuance,trailingCommonStockIssuance,annualNetIssuancePaymentsOfDebt,trailingNetIssuancePaymentsOfDebt,annualNetShortTermDebtIssuance,trailingNetShortTermDebtIssuance,annualShortTermDebtPayments,trailingShortTermDebtPayments,annualShortTermDebtIssuance,trailingShortTermDebtIssuance,annualNetLongTermDebtIssuance,trailingNetLongTermDebtIssuance,annualLongTermDebtPayments,trailingLongTermDebtPayments,annualLongTermDebtIssuance,trailingLongTermDebtIssuance,annualInvestingCashFlow,trailingInvestingCashFlow,annualCashFromDiscontinuedInvestingActivities,trailingCashFromDiscontinuedInvestingActivities,annualCashFlowFromContinuingInvestingActivities,trailingCashFlowFromContinuingInvestingActivities,annualNetOtherInvestingChanges,trailingNetOtherInvestingChanges,annualInterestReceivedCFI,trailingInterestReceivedCFI,annualDividendsReceivedCFI,trailingDividendsReceivedCFI,annualNetInvestmentPurchaseAndSale,trailingNetInvestmentPurchaseAndSale,annualSaleOfInvestment,trailingSaleOfInvestment,annualPurchaseOfInvestment,trailingPurchaseOfInvestment,annualNetInvestmentPropertiesPurchaseAndSale,trailingNetInvestmentPropertiesPurchaseAndSale,annualSaleOfInvestmentProperties,trailingSaleOfInvestmentProperties,annualPurchaseOfInvestmentProperties,trailingPurchaseOfInvestmentProperties,annualNetBusinessPurchaseAndSale,trailingNetBusinessPurchaseAndSale,annualSaleOfBusiness,trailingSaleOfBusiness,annualPurchaseOfBusiness,trailingPurchaseOfBusiness,annualNetIntangiblesPurchaseAndSale,trailingNetIntangiblesPurchaseAndSale,annualSaleOfIntangibles,trailingSaleOfIntangibles,annualPurchaseOfIntangibles,trailingPurchaseOfIntangibles,annualNetPPEPurchaseAndSale,trailingNetPPEPurchaseAndSale,annualSaleOfPPE,trailingSaleOfPPE,annualPurchaseOfPPE,trailingPurchaseOfPPE,annualCapitalExpenditureReported,trailingCapitalExpenditureReported,annualOperatingCashFlow,trailingOperatingCashFlow,annualCashFromDiscontinuedOperatingActivities,trailingCashFromDiscontinuedOperatingActivities,annualCashFlowFromContinuingOperatingActivities,trailingCashFlowFromContinuingOperatingActivities,annualTaxesRefundPaid,trailingTaxesRefundPaid,annualInterestReceivedCFO,trailingInterestReceivedCFO,annualInterestPaidCFO,trailingInterestPaidCFO,annualDividendReceivedCFO,trailingDividendReceivedCFO,annualDividendPaidCFO,trailingDividendPaidCFO,annualChangeInWorkingCapital,trailingChangeInWorkingCapital,annualChangeInOtherWorkingCapital,trailingChangeInOtherWorkingCapital,annualChangeInOtherCurrentLiabilities,trailingChangeInOtherCurrentLiabilities,annualChangeInOtherCurrentAssets,trailingChangeInOtherCurrentAssets,annualChangeInPayablesAndAccruedExpense,trailingChangeInPayablesAndAccruedExpense,annualChangeInAccruedExpense,trailingChangeInAccruedExpense,annualChangeInInterestPayable,trailingChangeInInterestPayable,annualChangeInPayable,trailingChangeInPayable,annualChangeInDividendPayable,trailingChangeInDividendPayable,annualChangeInAccountPayable,trailingChangeInAccountPayable,annualChangeInTaxPayable,trailingChangeInTaxPayable,annualChangeInIncomeTaxPayable,trailingChangeInIncomeTaxPayable,annualChangeInPrepaidAssets,trailingChangeInPrepaidAssets,annualChangeInInventory,trailingChangeInInventory,annualChangeInReceivables,trailingChangeInReceivables,annualChangesInAccountReceivables,trailingChangesInAccountReceivables,annualOtherNonCashItems,trailingOtherNonCashItems,annualExcessTaxBenefitFromStockBasedCompensation,trailingExcessTaxBenefitFromStockBasedCompensation,annualStockBasedCompensation,trailingStockBasedCompensation,annualUnrealizedGainLossOnInvestmentSecurities,trailingUnrealizedGainLossOnInvestmentSecurities,annualProvisionandWriteOffofAssets,trailingProvisionandWriteOffofAssets,annualAssetImpairmentCharge,trailingAssetImpairmentCharge,annualAmortizationOfSecurities,trailingAmortizationOfSecurities,annualDeferredTax,trailingDeferredTax,annualDeferredIncomeTax,trailingDeferredIncomeTax,annualDepreciationAmortizationDepletion,trailingDepreciationAmortizationDepletion,annualDepletion,trailingDepletion,annualDepreciationAndAmortization,trailingDepreciationAndAmortization,annualAmortizationCashFlow,trailingAmortizationCashFlow,annualAmortizationOfIntangibles,trailingAmortizationOfIntangibles,annualDepreciation,trailingDepreciation,annualOperatingGainsLosses,trailingOperatingGainsLosses,annualPensionAndEmployeeBenefitExpense,trailingPensionAndEmployeeBenefitExpense,annualEarningsLossesFromEquityInvestments,trailingEarningsLossesFromEquityInvestments,annualGainLossOnInvestmentSecurities,trailingGainLossOnInvestmentSecurities,annualNetForeignCurrencyExchangeGainLoss,trailingNetForeignCurrencyExchangeGainLoss,annualGainLossOnSaleOfPPE,trailingGainLossOnSaleOfPPE,annualGainLossOnSaleOfBusiness,trailingGainLossOnSaleOfBusiness,annualNetIncomeFromContinuingOperations,trailingNetIncomeFromContinuingOperations,annualCashFlowsfromusedinOperatingActivitiesDirect,trailingCashFlowsfromusedinOperatingActivitiesDirect,annualTaxesRefundPaidDirect,trailingTaxesRefundPaidDirect,annualInterestReceivedDirect,trailingInterestReceivedDirect,annualInterestPaidDirect,trailingInterestPaidDirect,annualDividendsReceivedDirect,trailingDividendsReceivedDirect,annualDividendsPaidDirect,trailingDividendsPaidDirect,annualClassesofCashPayments,trailingClassesofCashPayments,annualOtherCashPaymentsfromOperatingActivities,trailingOtherCashPaymentsfromOperatingActivities,annualPaymentsonBehalfofEmployees,trailingPaymentsonBehalfofEmployees,annualPaymentstoSuppliersforGoodsandServices,trailingPaymentstoSuppliersforGoodsandServices,annualClassesofCashReceiptsfromOperatingActivities,trailingClassesofCashReceiptsfromOperatingActivities,annualOtherCashReceiptsfromOperatingActivities,trailingOtherCashReceiptsfromOperatingActivities,annualReceiptsfromGovernmentGrants,trailingReceiptsfromGovernmentGrants,annualReceiptsfromCustomers,trailingReceiptsfromCustomers&merge=false&period1=0&period2={epoch}&corsDomain=finance.yahoo.com"
    r = requests.get(url, headers=headers).text
    return parse_yahoo_api(r)


# Financials
@return_None_on_error
def EBIT(ticker: yf.Ticker):
    # TODO: yfinance is inaccurate, already filed bug report on github
    return yahoo_api_get_financials_quarterly(ticker.ticker)['quarterlyEBIT'][-1]['reportedValue']['raw']


@return_None_on_error
def EBITDA(ticker: yf.Ticker):
    return EBIT(ticker) + depreciation_and_amortization(ticker)


@return_None_on_error
def depreciation(ticker: yf.Ticker):
    return yahoo_api_get_financials_quarterly(ticker.ticker)['quarterlyReconciledDepreciation'][-1]['reportedValue']['raw']


@return_None_on_error
def interest_expense(ticker: yf.Ticker):
    return abs(ticker.quarterly_financials.iloc[:, 0]['Interest Expense'])


@return_None_on_error
def operating_income(ticker: yf.Ticker):
    return ticker.quarterly_financials.iloc[:, 0]['Operating Income']


@return_None_on_error
def net_income(ticker: yf.Ticker):
    return ticker.quarterly_financials.iloc[:, 0]['Net Income']


@return_None_on_error
def revenue(ticker: yf.Ticker):
    return ticker.quarterly_balance_sheet.iloc[:, 0]['Total Revenue']


@return_None_on_error
def cost_of_revenue(ticker: yf.Ticker):
    return ticker.quarterly_balance_sheet.iloc[:, 0]['Cost Of Revenue']


# Balance sheet
@return_None_on_error
def total_assets(ticker: yf.Ticker):
    return ticker.quarterly_balance_sheet.iloc[:, 0]['Total Assets']


@return_None_on_error
def current_assets(ticker: yf.Ticker):
    return ticker.quarterly_balance_sheet.iloc[:, 0]['Total Current Assets']


@return_None_on_error
def total_liabilities(ticker: yf.Ticker):
    return ticker.quarterly_balance_sheet.iloc[:, 0]['Total Liab']


@return_None_on_error
def current_liabilities(ticker: yf.Ticker):
    return ticker.quarterly_balance_sheet.iloc[:, 0]['Total Current Liabilities']


@return_None_on_error
def total_debt(ticker: yf.Ticker):
    return yahoo_api_get_balance_sheet_quarterly(ticker.ticker)['quarterlyTotalDebt'][-1]['reportedValue']['raw']


@return_None_on_error
def current_debt(ticker: yf.Ticker):
    return ticker.quarterly_balance_sheet.iloc[:, 0]['Short Long Term Debt']


@return_None_on_error
def retained_earnings(ticker: yf.Ticker):
    return ticker.quarterly_balance_sheet.iloc[:, 0]['Retained Earnings']


@return_None_on_error
def tangible_book_value(ticker: yf.Ticker):
    return ticker.quarterly_balance_sheet.iloc[:, 0]['Net Tangible Assets']


@return_None_on_error
def inventory(ticker: yf.Ticker):
    return ticker.quarterly_balance_sheet.iloc[:, 0]['Inventory']


@return_None_on_error
def cash(ticker: yf.Ticker):
    return ticker.quarterly_balance_sheet.iloc[:, 0]['Cash']


@return_None_on_error
def intangible_assets(ticker: yf.Ticker):  # includes goodwill
    return ticker.quarterly_balance_sheet.iloc[:, 0]['Intangible Assets'] + ticker.quarterly_balance_sheet.iloc[:, 0]['Good Will']


@return_None_on_error
def invested_capital(ticker: yf.Ticker):
    return yahoo_api_get_balance_sheet_quarterly(ticker.ticker)['quarterlyInvestedCapital'][-1]['reportedValue']['raw']


# Cashflow
@return_None_on_error
def operating_cash_flow(ticker: yf.Ticker):
    return ticker.quarterly_cashflow.iloc[:, 0]['Total Cash From Operating Activities']


@return_None_on_error
def depreciation_and_amortization(ticker: yf.Ticker):
    return yahoo_api_get_cashflow_quarterly(ticker.ticker)['quarterlyDepreciationAmortizationDepletion'][-1]['reportedValue']['raw']


@return_None_on_error
def altman_z_score(ticker: yf.Ticker):
    x1 = (current_assets(ticker) - current_liabilities(ticker)) / total_assets(ticker)
    x2 = retained_earnings(ticker) / total_assets(ticker)
    x3 = EBIT(ticker) / total_assets(ticker)
    x4 = tangible_book_value(ticker) / total_liabilities(ticker)
    z = 6.56 * x1 + 3.26 * x2 + 6.72 * x3 + 1.05 * x4
    return z


# Ratios
# Liquidity (higher the better)
@return_None_on_error
def quick_ratio(ticker: yf.Ticker):  # key
    return (current_assets(ticker) - inventory(ticker)) / current_liabilities(ticker)


@return_None_on_error
def cash_ratio(ticker: yf.Ticker):
    return cash(ticker) / current_liabilities(ticker)


@return_None_on_error
def operating_cash_ratio(ticker: yf.Ticker):
    return operating_cash_flow(ticker) / current_liabilities(ticker)


# Coverage ratios (higher the better)
@return_None_on_error
def interest_coverage_ratio(ticker: yf.Ticker):
    return EBITDA(ticker) / interest_expense(ticker)


@return_None_on_error
def debt_service_coverage_ratio(ticker: yf.Ticker):  # key
    return operating_income(ticker) / interest_expense(ticker)


@return_None_on_error
def asset_coverage_ratio(ticker: yf.Ticker):
    return (total_assets(ticker) - intangible_assets(ticker) - (current_liabilities(ticker) - current_debt(ticker))) / total_debt(ticker)


@return_None_on_error
def cash_coverage_ratio(ticker: yf.Ticker):
    return (EBIT(ticker) + depreciation(ticker)) / interest_expense(ticker)


# Leverage ratios (lower the better)
@return_None_on_error
def total_debt_to_tangible_book_value_ratio(ticker: yf.Ticker):
    return total_debt(ticker) / tangible_book_value(ticker)


@return_None_on_error
def total_debt_to_total_assets_ratio(ticker: yf.Ticker):  # key
    return total_debt(ticker) / total_assets(ticker)


@return_None_on_error
def total_debt_to_EBITDA_ratio(ticker: yf.Ticker):  # key
    return total_debt(ticker) / EBITDA(ticker)


# Piotroski’s F-score
@return_None_on_error
def ROIC(ticker: yf.Ticker):
    return net_income(ticker) / invested_capital(ticker)


@return_None_on_error
def delta_ROIC(ticker: yf.Ticker):
    old = ticker.financials.iloc[:, -1]['Net Income'] / yahoo_api_get_balance_sheet_yearly(ticker.ticker)['annualInvestedCapital'][0]['reportedValue']['raw']
    new = ticker.financials.iloc[:, 0]['Net Income'] / yahoo_api_get_balance_sheet_yearly(ticker.ticker)['annualInvestedCapital'][-1]['reportedValue']['raw']
    return new - old


@return_None_on_error
def delta_total_debt_to_EBITDA(ticker: yf.Ticker):
    old = yahoo_api_get_balance_sheet_yearly(ticker.ticker)['annualTotalDebt'][0]['reportedValue']['raw'] / (
                yahoo_api_get_financials_yearly(ticker.ticker)['annualEBIT'][0]['reportedValue']['raw'] +
                yahoo_api_get_cashflow_yearly(ticker.ticker)['annualDepreciationAmortizationDepletion'][0]['reportedValue']['raw'])
    new = yahoo_api_get_balance_sheet_yearly(ticker.ticker)['annualTotalDebt'][-1]['reportedValue']['raw'] / (
                yahoo_api_get_financials_yearly(ticker.ticker)['annualEBIT'][-1]['reportedValue']['raw'] +
                yahoo_api_get_cashflow_yearly(ticker.ticker)['annualDepreciationAmortizationDepletion'][0]['reportedValue']['raw'])
    return new - old


@return_None_on_error
def delta_total_debt_to_total_asset(ticker: yf.Ticker):
    old = yahoo_api_get_balance_sheet_yearly(ticker.ticker)['annualTotalDebt'][0]['reportedValue']['raw'] / ticker.balance_sheet.iloc[:, -1]['Total Assets']
    new = yahoo_api_get_balance_sheet_yearly(ticker.ticker)['annualTotalDebt'][-1]['reportedValue']['raw'] / ticker.balance_sheet.iloc[:, 0]['Total Assets']
    return new - old


@return_None_on_error
def delta_quick_ratio(ticker: yf.Ticker):
    old = (ticker.balance_sheet.iloc[:, -1]['Total Current Assets'] - ticker.balance_sheet.iloc[:, -1]['Inventory']) / ticker.balance_sheet.iloc[:, -1]['Total Current Liabilities']
    new = (ticker.balance_sheet.iloc[:, 0]['Total Current Assets'] - ticker.balance_sheet.iloc[:, 0]['Inventory']) / ticker.balance_sheet.iloc[:, 0]['Total Current Liabilities']
    return new - old


@return_None_on_error
def delta_gross_profit(ticker: yf.Ticker):
    old = ticker.balance_sheet.iloc[:, -1]['Total Revenue'] - ticker.balance_sheet.iloc[:, -1]['Cost Of Revenue']
    new = ticker.balance_sheet.iloc[:, 0]['Total Revenue'] - ticker.balance_sheet.iloc[:, 0]['Cost Of Revenue']
    return new - old


@return_None_on_error
def delta_revenue_to_total_assets(ticker: yf.Ticker):
    old = ticker.balance_sheet.iloc[:, -1]['Total Revenue'] / ticker.quarterly_balance_sheet.iloc[:, -1]['Total Assets']
    new = ticker.balance_sheet.iloc[:, 0]['Total Revenue'] / ticker.quarterly_balance_sheet.iloc[:, 0]['Total Assets']
    return new - old


@return_None_on_error
def F_score(ticker: yf.Ticker):
    score = 0
    # Profitability
    if ROIC(ticker) > 0:
        score += 1
    if operating_cash_flow(ticker) > 0:
        score += 1
    if delta_ROIC(ticker) > 0:
        score += 1
    if operating_cash_flow(ticker) / invested_capital(ticker) > ROIC(ticker):
        score += 1
    # Leverage, Liquidity and Source of Funds
    if delta_total_debt_to_EBITDA(ticker) > 0 and delta_total_debt_to_total_asset(ticker) < 0:
        score += 1
    if delta_quick_ratio(ticker) > 0:
        score += 1
    # Operating Efficiency
    if delta_gross_profit(ticker) > 0:
        score += 1
    if delta_revenue_to_total_assets(ticker) > 0:
        score += 1
    return score
